### ISSUE TITLE
Make  sure CodeCheck covers all CodePatch cases

### ISSUE THREAD

**Issue by gldeng** [AElfProject/AElf#3381]
**Current State**
When deploying a smart contract, a user sends a proposal to for the deployment and the code will be deployed after 2/3 of the BPs have approved it. BP will manually check the code to make sure it conforms to the required security and operation standards.

**New**
In 1.3.0, the BP node client will perform CodeCheck on deployed `UserContract` automatically. BPs will automatically approve the contract if the CodeCheck is passed and  once 2/3 of the BPs approved the deployment it will be released and users can start to interact with the smart contract. One of the requirements is the deployed contract have to be correctly patched so that it can be executed securely on the blockchain.

As the CodeCheck is automatically done, we need to make sure CodeCheck covers all the cases required in CodePatch.

**Task Breakdown**
- [ ] Prepare test cases for missing coverage
- [ ] Add missed CodeCheck cases
- [ ] Refactor existing test cases to have more fine-grained test cases **(Optional)**
- [ ] Refactor CodeCheck and CodePatcher for better flexibility on usage **(Optional)**
