### ISSUE TITLE
[WIP] Refactoring consensus module.

### ISSUE THREAD

**Issue by EanCuznaivy** [AElfProject/AElf#888]
**Purpose**

1. Adjust contract code to apply to new consensus process.

2. To support random number generation.

**TODO List**

- [x] Reorg current contract code.

- [x] Re-design contract methods.

- [x] Split in value to several parts and encode them.

- [x] Random number validation.

**Comment by EanCuznaivy** [comment]
Working on branch refactor/consensus-contracts
