### ISSUE TITLE
[tracking] network improvements

### ISSUE THREAD

**Issue by samfrb** [AElfProject/AElf#940]
Tracking issue for network fixes/improvements:
- [x] better disconnection handling
- [x] matching peers on public key (issue #1046, issue #1045)
- [x] improve authentication mechanism
- [x] peer request choice when syncing (issue #1042)
- [x] redesign network tests (#1232)

[ removed ] use an existing class for representing an URI: it seems the uri format is not parsable by dotnet Uri/UriBuilder classes.
